local Players=game:GetService("Players"); local RS=game:GetService("ReplicatedStorage"); local Terrain=workspace.Terrain
local C=require(RS:WaitForChild("Valbrume"):WaitForChild("Config")); local Data=require(script.Parent:WaitForChild("PlayerDataService"))
local Generation = require(script.Parent.WorldGeneration)
local world = Generation.Await("Continents")
local Atlas=require(RS.Valbrume.ContinentAtlas)
local Continents=require(script.Parent.ContinentsRuntime)
local expansion=world:WaitForChild("ExpansionV25"); local zones=expansion:WaitForChild("Zones"); local root=world:WaitForChild("OpenWorldV28"); local poi=root:WaitForChild("POI"); local hazards=root:WaitForChild("Hazards"); local sea=root:WaitForChild("SeaTravel")
local function part(parent,name,size,cf,color,material,t) local p=Instance.new("Part"); p.Name=name; p.Size=size; p.CFrame=cf; p.Anchored=true; p.CanCollide=true; p.CanTouch=false; p.Color=color; p.Material=material or Enum.Material.Slate; p.Transparency=t or 0; p.Parent=parent; return p end
local function label(a,title,sub,color) local g=Instance.new("BillboardGui"); g.Adornee=a; g.Size=UDim2.fromOffset(270,72); g.StudsOffsetWorldSpace=Vector3.new(0,7,0); g.AlwaysOnTop=true; g.MaxDistance=125; g.Parent=a; local x=Instance.new("TextLabel"); x.Size=UDim2.fromScale(1,1); x.BackgroundTransparency=1; x.Text=title.."\n"..sub; x.TextColor3=color; x.TextStrokeTransparency=.25; x.Font=Enum.Font.GothamBold; x.TextSize=15; x.TextWrapped=true; x.Parent=g end
local function center(id) if C.Zones[id] then return C.Zones[id].Origin end; local s=zones:FindFirstChild(id.."_ExpansionSpawn"); return s and Vector3.new(s.Position.X,0,s.Position.Z) end
local function safePivot(player,cf) local ch=player.Character; local rp=ch and ch:FindFirstChild("HumanoidRootPart"); if ch and rp then ch:PivotTo(cf); rp.AssemblyLinearVelocity=Vector3.zero; rp.AssemblyAngularVelocity=Vector3.zero end end
local n4=center("N4"); if n4 then for _,o in ipairs({Vector3.new(-70,11,120),Vector3.new(35,9,150),Vector3.new(120,7,80)}) do Terrain:FillBall(n4+o,32,Enum.Material.Water) end; local fall=part(poi,"N4_Waterfall",Vector3.new(18,58,4),CFrame.new(n4+Vector3.new(-145,48,105)),Color3.fromRGB(153,207,224),Enum.Material.Glass,.35); fall.CanCollide=false; label(fall,"Chute de Nacre","Embruns des Caps de Nacre",Color3.fromRGB(181,224,237)) end
local lava={}; local o5=center("O5"); if o5 then for i,d in ipairs({{Vector3.new(-90,13,-75),36},{Vector3.new(55,11,-120),30},{Vector3.new(125,9,25),42}}) do local pos=o5+d[1]; Terrain:FillBall(pos-Vector3.new(0,8,0),d[2],Enum.Material.CrackedLava); local g=part(hazards,"Lava_O5_"..i,Vector3.new(d[2]*1.55,1.2,d[2]*1.55),CFrame.new(pos+Vector3.new(0,1,0)),Color3.fromRGB(242,91,31),Enum.Material.Neon,.12); g.CanCollide=false; g.CanQuery=false; table.insert(lava,{Position=pos,Radius=d[2]*.78}) end; local f=part(poi,"O5_GrandFourneau",Vector3.new(24,60,24),CFrame.new(o5+Vector3.new(138,42,88)),Color3.fromRGB(76,69,66),Enum.Material.Basalt); label(f,"Grand Fourneau","Les Forges d'Ormefer ne sont pas éteintes.",Color3.fromRGB(235,139,78)) end
local v6=center("V6"); if v6 then for i=1,14 do local a=i*2.13; local r=65+(i%5)*27; local x,z=math.cos(a)*r,math.sin(a)*r; local c=part(poi,"V6_Crystal_"..i,Vector3.new(4+(i%3)*2,13+(i%5)*4,4+(i%2)*2),CFrame.new(v6+Vector3.new(x,34,z))*CFrame.Angles(math.rad(i%3*6),0,math.rad((i%5-2)*7)),i%3==0 and Color3.fromRGB(105,210,229) or Color3.fromRGB(173,111,225),Enum.Material.Glass,.08); c.CanCollide=false end end
local function dock(name,pos,face,title) local m=Instance.new("Model"); m.Name=name; m.Parent=sea; local d=part(m,"Deck",Vector3.new(18,3,78),CFrame.lookAt(pos,pos+face),Color3.fromRGB(106,76,49),Enum.Material.WoodPlanks); m.PrimaryPart=d; for _,x in ipairs({-31,-12,12,31}) do for _,s in ipairs({-1,1}) do part(m,"Post",Vector3.new(3,12,3),CFrame.new(pos+d.CFrame.LookVector*x+d.CFrame.RightVector*s*7-Vector3.new(0,4.5,0)),Color3.fromRGB(83,59,40),Enum.Material.Wood) end end; label(d,title,"Traversée de la Mer d'Obsidienne",Color3.fromRGB(225,208,163)); return m end
local west=dock("ElyndraDock",Vector3.new(-505,16,0),Vector3.new(1,0,0),"Quai d'Elyndra"); local east=dock("VarkhunDock",Vector3.new(505,16,0),Vector3.new(-1,0,0),"Quai de Varkhûn")
local ship=Instance.new("Model"); ship.Name="Ferry_Obsidienne"; ship.Parent=sea; local hull=part(ship,"Hull",Vector3.new(54,9,18),CFrame.new(0,12,0),Color3.fromRGB(72,51,38),Enum.Material.WoodPlanks); part(ship,"Deck",Vector3.new(42,2,15),CFrame.new(0,18,0),Color3.fromRGB(112,80,52),Enum.Material.WoodPlanks); part(ship,"Mast",Vector3.new(2,34,2),CFrame.new(0,34,0),Color3.fromRGB(78,56,42),Enum.Material.Wood); local sail=part(ship,"Sail",Vector3.new(1,22,18),CFrame.new(0,36,0),Color3.fromRGB(205,195,171),Enum.Material.Fabric); sail.CanCollide=false; ship.PrimaryPart=hull
local function prompt(from,to,title) local p=Instance.new("ProximityPrompt"); p.Name="CrossSea"; p.ActionText="Embarquer"; p.ObjectText="Vers "..title; p.HoldDuration=.7; p.MaxActivationDistance=14; p.RequiresLineOfSight=false; p.Parent=from.PrimaryPart; p.Triggered:Connect(function(player) player:SetAttribute("VBExpansionTravel",true); player:SetAttribute("VBExpansionZone",nil); safePivot(player,to.PrimaryPart.CFrame+to.PrimaryPart.CFrame.LookVector*22+Vector3.new(0,6,0)) end) end
prompt(west,east,"Varkhûn"); prompt(east,west,"Elyndra")
local centers={}; for _,id in ipairs({"A2","S3","N4","H2","O5","V6"}) do centers[id]=center(id) end; local ex={S3=true,N4=true,O5=true,V6=true}
local function hd(a,b) return Vector2.new(a.X-b.X,a.Z-b.Z).Magnitude end; local function nearest(pos) return Atlas.resolve(pos.X,pos.Z) end
task.spawn(function() while true do task.wait(.35); for _,player in ipairs(Players:GetPlayers()) do local ch=player.Character; local rp=ch and ch:FindFirstChild("HumanoidRootPart"); local profile=Data.Get(player); if rp and not player:GetAttribute("VBDungeonId") and profile and profile.Zone and centers[profile.Zone] then local region,dist,continent=nearest(rp.Position); player:SetAttribute("VBContinentId",continent); local home=hd(rp.Position,centers[profile.Zone]); if region then player:SetAttribute("VBRegionId",region) end; if home>265 then player:SetAttribute("VBExpansionTravel",true) else player:SetAttribute("VBExpansionTravel",nil) end; if ex[region] and dist<=560 then player:SetAttribute("VBExpansionZone",region); player:SetAttribute("VBExpansionTravel",true) elseif region=="A2" or region=="H2" then player:SetAttribute("VBExpansionZone",nil); if region~=profile.Zone then player:SetAttribute("VBExpansionTravel",true) end else player:SetAttribute("VBExpansionZone",nil); player:SetAttribute("VBExpansionTravel",true) end end end end end)
task.spawn(function() while true do task.wait(.75); for _,player in ipairs(Players:GetPlayers()) do local ch=player.Character; local h=ch and ch:FindFirstChildOfClass("Humanoid"); local rp=ch and ch:FindFirstChild("HumanoidRootPart"); if h and rp and h.Health>0 then for _,z in ipairs(lava) do local d=rp.Position-z.Position; if Vector2.new(d.X,d.Z).Magnitude<=z.Radius and math.abs(d.Y)<=20 then h:TakeDamage(math.max(8,h.MaxHealth*.08)); break end end end end end end)
print("[Valbrume V2.8] Biomes : eau, lave, cristaux, ferry et détection open-world actifs.")

Continents.prepare(world)
-- Bounded S3-P6 landscape worksite; base six-link repair remains unchanged.
local LandscapeS3P6=require(script.Parent.LandscapeS3P6.Build)
LandscapeS3P6.run(world)
Generation.Complete(world, "Biome")
if game:GetService("RunService"):IsStudio() then
    task.spawn(function()
        local ok,err=pcall(function() Generation.Await("Ready"); Continents.audit(world); LandscapeS3P6.audit(world) end)
        if not ok then warn("[VALBRUME CONTINENTS QA] "..tostring(err)) end
    end)
end
