local Players=game:GetService("Players"); local RS=game:GetService("ReplicatedStorage"); local Terrain=workspace.Terrain
local package=RS:WaitForChild("Valbrume"); local C=require(package:WaitForChild("Config")); local server=script.Parent; local Data=require(server:WaitForChild("PlayerDataService"))
local Generation = require(script.Parent.WorldGeneration)
local world = Generation.Await("Expansion")
local expansion=world.ExpansionV25; local zones=expansion:WaitForChild("Zones"); local oldTravel=expansion:FindFirstChild("Travel"); if oldTravel then oldTravel:Destroy() end
local oldRoot=world:FindFirstChild("OpenWorldV28"); if oldRoot then oldRoot:Destroy() end
local root=Instance.new("Folder"); root.Name="OpenWorldV28"; root.Parent=world; local roads=Instance.new("Folder"); roads.Name="Roads"; roads.Parent=root; local poi=Instance.new("Folder"); poi.Name="POI"; poi.Parent=root; local sea=Instance.new("Folder"); sea.Name="SeaTravel"; sea.Parent=root; local hazards=Instance.new("Folder"); hazards.Name="Hazards"; hazards.Parent=root
local function part(parent,name,size,cf,color,material,t) local p=Instance.new("Part"); p.Name=name; p.Size=size; p.CFrame=cf; p.Anchored=true; p.CanCollide=true; p.CanTouch=false; p.Color=color; p.Material=material or Enum.Material.Slate; p.Transparency=t or 0; p.TopSurface=Enum.SurfaceType.Smooth; p.BottomSurface=Enum.SurfaceType.Smooth; p.Parent=parent; return p end
local function label(a,title,sub,color) local g=Instance.new("BillboardGui"); g.Adornee=a; g.Size=UDim2.fromOffset(280,76); g.StudsOffsetWorldSpace=Vector3.new(0,7,0); g.AlwaysOnTop=true; g.MaxDistance=130; g.Parent=a; local x=Instance.new("TextLabel"); x.Size=UDim2.fromScale(1,1); x.BackgroundTransparency=1; x.Text=title.."\n"..sub; x.TextColor3=color; x.TextStrokeTransparency=.25; x.Font=Enum.Font.GothamBold; x.TextSize=15; x.TextWrapped=true; x.Parent=g end
local function groundY(x,z,f) local pa=RaycastParams.new(); pa.FilterType=Enum.RaycastFilterType.Include; pa.FilterDescendantsInstances={Terrain}; pa.IgnoreWater=true; local h=workspace:Raycast(Vector3.new(x,320,z),Vector3.new(0,-700,0),pa); return h and h.Position.Y or f end
local function spawnOf(id) if C.Zones[id] then return world:FindFirstChild(id.."Spawn") end; return zones:FindFirstChild(id.."_ExpansionSpawn") end
local function center(id) if C.Zones[id] then return C.Zones[id].Origin end; local s=spawnOf(id); return s and Vector3.new(s.Position.X,0,s.Position.Z) end
local names={A2="Val d'Astréa",S3="Sylvebrume",N4="Caps de Nacre",H2="Terres cendrées de Khar",O5="Forges d'Ormefer",V6="Profondeurs de l'Écho"}
Terrain:FillBlock(CFrame.new(0,-17,0),Vector3.new(900,50,2300),Enum.Material.Water); Terrain:FillBlock(CFrame.new(-500,8,0),Vector3.new(160,20,2100),Enum.Material.Sand); Terrain:FillBlock(CFrame.new(500,8,0),Vector3.new(160,20,2100),Enum.Material.Sand)
for i,pos in ipairs({Vector3.new(-155,5,-430),Vector3.new(140,6,360),Vector3.new(-60,4,780)}) do Terrain:FillBall(pos,68-i*7,Enum.Material.Rock); Terrain:FillBall(pos+Vector3.new(0,15,0),44-i*4,Enum.Material.Grass) end
local routes={{"A2_S3","A2","S3","Passage des Racines",Enum.Material.Ground,Color3.fromRGB(91,119,89)},{"A2_N4","A2","N4","Col des Embruns",Enum.Material.Slate,Color3.fromRGB(111,132,141)},{"H2_O5","H2","O5","Défilé des Scories",Enum.Material.Basalt,Color3.fromRGB(116,82,66)},{"H2_V6","H2","V6","Faille des Murmures",Enum.Material.Rock,Color3.fromRGB(104,87,125)}}
local function route(r) local a,b=center(r[2]),center(r[3]); if not a or not b then return end; local folder=Instance.new("Folder"); folder.Name=r[1]; folder.Parent=roads; local n=24; for i=0,n do local t=i/n; local x=a.X+(b.X-a.X)*t; local z=a.Z+(b.Z-a.Z)*t; local y=groundY(x,z,20+math.sin(t*math.pi)*4); Terrain:FillBall(Vector3.new(x,y-40,z),40,r[5]); if i%2==0 and i<n then local nt=(i+1)/n; local nx=a.X+(b.X-a.X)*nt; local nz=a.Z+(b.Z-a.Z)*nt; local d=Vector3.new(nx-x,0,nz-z); if d.Magnitude>.1 then part(folder,"Path",Vector3.new(17,1.1,d.Magnitude+10),CFrame.lookAt(Vector3.new(x,y+1.2,z),Vector3.new(nx,y+1.2,nz)),r[6],r[5]) end end end; local m=(a+b)*.5; local y=groundY(m.X,m.Z,24); local s=part(poi,r[1].."_Marker",Vector3.new(5,10,5),CFrame.new(m.X,y+5,m.Z),r[6],Enum.Material.Slate); label(s,r[4],names[r[2]].." ↔ "..names[r[3]],r[6]) end
for _,r in ipairs(routes) do route(r) end

Generation.Complete(world, "Continents")
